//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.14 at 10:01:31 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.intellect.com/spring/soap/api/loanEligibility", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.intellect.spring.soap.api.loaneligibility;
